config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "spends#index"
  resources :spends
  get "share", params: :token, controller: "spends", action: "share_show"
  post "generate_link", to: "user#generate_link", xhr: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/spend.rb
class Spend < ApplicationRecord

  scope :filter_by_amount, -> (order){ order(amount: order) }
  scope :filter_by_category, -> (category){ where(category: category) }

  enum :category, [:traveling, :clothing, :taxi, :cafes, :shops, :other]
  validates :title, presence: true
  validates :amount, presence: true
  belongs_to :user

  filterrific(
    default_filter_params: { filter_by_amount: 'desc' },
    available_filters:[
    :filter_by_amount,
    :filter_by_category
  ])
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spends

  def total_spends_value
    total_value = 0
    spends.each do |spend|
      total_value += spend.amount
    end
    total_value
  end

    def generate_token
      self.update(url_token: SecureRandom.urlsafe_base64(64, false))
      url_token
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/spends_controller.rb
class SpendsController < ApplicationController
  before_action :authenticate_user!, except: :share_show
  before_action :has_access?, only: [:show, :edit, :destroy]
  def index
    @filterrific = initialize_filterrific(
      current_user.spends,
      params[:filterrific]
    ) or return
    @spends = @filterrific.find
  end

  def new
    @spend = Spend.new
  end

  def show
    @spend = Spend.find_by(id: params[:id])
  end

  def edit
    @spend = Spend.find_by(id: params[:id])
  end

  def create
    spend = Spend.new(spend_params)
    spend.user = current_user
    if spend.save
      redirect_to root_path
    else
      flash[:errors] = spend.errors.full_messages
      redirect_to new_spend_path
    end
  end

  def destroy
    spend = Spend.find_by(id: params[:id])
    spend.destroy
    redirect_to root_path, status: :see_other
  end

  def share_show
    user = User.find_by(url_token: params[:token])
    return redirect_to root_path if user.nil?
    @share_spends = user.spends
  end

  private
  def spend_params
    params.require(:spend).permit(:title, :description, :amount, :category)
  end

  def has_access?
    redirect_to root_path unless Spend.find_by(id: params[:id]).user == current_user
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def generate_link
    @token = current_user.generate_token
    respond_to do |format|
      format.js {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spends_helper.rb
module SpendsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Ninth navbar example">
    <div class="container-xl">
      <a class="navbar-brand" href="/">Track App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarsExample07XL">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "New spend", new_spend_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Share list", generate_link_url, data: {remote: true, type: "script", method: :post}, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
          </li>
        </ul>
      </div>
      <% end %>
    </div>
  </nav>

  <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <div>
    <% if message.is_a?(Array) %>
      <% message.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    <% else %>
      <%= message %>
    <% end %>
  </div>
<% end %>

app/views/spends/edit.html.erb
<%= form_for @spend, url: spend_path(@spend), method: :post do |f| %>
  <div class="form-group">
    <label for="title">Title</label>
    <%= f.text_field :title, id:"title", class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="description">Description</label>
    <%= f.text_area :description, id:"description", class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="amount">Amount</label>
    <%= f.number_field :amount, id:"amount", class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="category">Category</label>
    <%= f.select(:category, options_for_select(Spend.categories.map { |key, value| [key.humanize, key] }), {}, {class:"form-control form-control-sm", id:"category"})  %>
  </div>
  <p><%= f.submit "Update", class:"btn btn-primary" %></p>
<% end %>

app/views/spends/index.html.erb
<div class="shared_link"></div>
<div class="filter">
  <%= form_for_filterrific @filterrific do |f| %>
    <div>
      <div>
        Amount by
        <%= f.select(:filter_by_amount, ["desc", "asc"]) %>
      </div>
      <div>
        Category
        <%= f.select(:filter_by_category, Spend.categories,{ include_blank: '- Any -' }) %>
      </div>
      <div>
        <%= f.submit 'Filter' %>
      </div>
    </div>

    <div>
      <%= link_to(
            'Reset filters',
            reset_filterrific_url,
            ) %>
    </div>
  <%end %>
</div>

<hr>
<div class="content">
  <div class="spends">
    <% @spends.each do |spend| %>
      <div class="spend">
        <%= link_to spend.title, spend_url(spend) %>
        <p>Description: <%= spend.description %></p>
        <p>Amount: <%= spend.amount %></p>
        <p>Category: <%= spend.category %></p>
      </div>
    <% end %>
</div>
  <div class="info">
    <p>Your total spends value: <%= current_user.total_spends_value %></p>
  </div>
</div>

app/views/spends/new.html.erb
<%= form_for @spend, url: spends_path, method: :post do |f| %>
  <div class="form-group">
    <label for="title">Title</label>
    <%= f.text_field :title, id:"title", class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="description">Description</label>
    <%= f.text_area :description, id:"description", class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="amount">Amount</label>
    <%= f.number_field :amount, id:"amount", class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="category">Category</label>
    <%= f.select(:category, options_for_select(Spend.categories.map { |key, value| [key.humanize, key] }), {}, {class:"form-control form-control-sm", id:"category"})  %>
  </div>
  <p><%= f.submit "Create", class:"btn btn-primary" %></p>
<% end %>

app/views/spends/share_show.html.erb
<% @share_spends.each do |spend| %>
  <div>
    <%= spend.title %>
    <p>Description: <%= spend.description %></p>
    <p>Amount: <%= spend.amount %></p>
    <p>Category: <%= spend.category %></p>
  </div>
<% end %>

app/views/spends/show.html.erb
<div>
  <p>Title: <%= @spend.title %></p>
  <p>Description: <%= @spend.description %></p>
  <p>Amount: <%= @spend.amount %></p>
  <p>Category: <%= @spend.category %></p>
  <%= link_to "Delete", spend_path(@spend), data: { "turbo-method": :delete } %>
  <%= link_to "Edit", edit_spend_path(@spend) %>
</div>

app/views/user/generate_link.js.erb
$(".shared_link").html("Your shared link: " + window.location.origin + "/share?token=" + "<%= @token %>")